const img1 = "https://i.postimg.cc/gcDzWF7x/1.webp";
const img2 = "https://i.postimg.cc/Fz9hLDYF/2.webp";
const img3 = "https://i.postimg.cc/vT3bLfnr/3.webp";
const img4 = "https://i.postimg.cc/vT3bLfnr/3.webp";


export const productsArray = [img1,img2,img3,img4];

export const productsDB = [
	{id: 1, url: img1, 	title: "bomber shivan black",season: "spring",type: "torso", price: 600},
	{id: 2, url: img2, 	title: "bomber shivan black",season: "summer",type: "head", price: 900},
	{id: 3, url: img3, 	title: "T-shirt long black", season: "spring",type: "legs", price: 300},
	{id: 4, url: img4, 	title: "Pants blue black",   season: "summer",type: "torso", price: 450},
	{id: 5, url: img1, 	title: "Gloves green black", season: "summer",type: "feet", price: 260},
	{id: 6, url: img2, 	title: "something black",    season: "winter",type: "torso", price: 400},
	{id: 7, url: img3, 	title: "other product black",season: "spring",type: "feet", price: 100},
	{id: 8, url: img4, 	title: "Sweater black",		 season: "spring",type: "head", price: 700},
	{id: 9, url: img1, 	title: "bomber shivan black",season: "winter",type: "feet", price: 260},
	{id: 10, url: img2, title: "bomber shivan black",season: "winter",type: "feet", price: 400},
	{id: 11, url: img3, title: "bomber shivan black",season: "winter",type: "legs", price: 100},
	{id: 12, url: img4, title: "bomber shivan black",season: "autumn",type: "feet", price: 700},
	{id: 13, url: img4, title: "bomber shivan black",season: "autumn",type: "legs", price: 700},
	{id: 14, url: img2, title: "bomber shivan black",season: "autumn",type: "head", price: 700},
	{id: 15, url: img1, title: "bomber shivan black",season: "autumn",type: "legs", price: 700},
	{id: 16, url: img3, title: "bomber shivan black",season: "winter",type: "torso", price: 400},
	{id: 17, url: img1, title: "bomber shivan black",season: "spring",type: "legs", price: 100},
	{id: 18, url: img3, title: "bomber shivan black",season: "spring",type: "legs", price: 700},
	{id: 19, url: img2, title: "bomber shivan black",season: "winter",type: "legs", price: 260},
	{id: 20, url: img1, title: "bomber shivan black",season: "winter",type: "torso", price: 400},
	{id: 21, url: img3, title: "bomber shivan black",season: "winter",type: "head", price: 100},
	{id: 22, url: img2, title: "bomber shivan black",season: "winter",type: "head", price: 400},
	{id: 23, url: img3, title: "bomber shivan black",season: "spring",type: "head", price: 100},
	{id: 24, url: img4, title: "bomber shivan black",season: "spring",type: "head", price: 700},
	{id: 25, url: img1, title: "bomber shivan black",season: "winter",type: "head", price: 260},
	{id: 26, url: img2, title: "bomber shivan black",season: "winter",type: "head", price: 400},
	{id: 27, url: img3, title: "bomber shivan black",season: "winter",type: "torso", price: 100},
	{id: 28, url: img1, title: "bomber shivan black",season: "winter",type: "head", price: 100},
	{id: 29, url: img2, title: "bomber shivan black",season: "winter",type: "head", price: 400},
	{id: 30, url: img3, title: "bomber shivan black",season: "spring",type: "head", price: 100},
	{id: 31, url: img4, title: "bomber shivan black",season: "summer",type: "legs", price: 700},
	{id: 32, url: img1, title: "bomber shivan black",season: "summer",type: "legs", price: 260},
	{id: 33, url: img2, title: "bomber shivan black",season: "winter",type: "head", price: 400},
	{id: 34, url: img3, title: "bomber shivan black",season: "winter",type: "torso", price: 100},
	{id: 35, url: img3, title: "bomber shivan black",season: "winter",type: "head", price: 100},
	{id: 36, url: img2, title: "bomber shivan black",season: "winter",type: "head", price: 400},
	{id: 37, url: img3, title: "bomber shivan black",season: "spring",type: "head", price: 100},
	{id: 38, url: img4, title: "bomber shivan black",season: "spring",type: "head", price: 700},
	{id: 39, url: img1, title: "bomber shivan black",season: "winter",type: "head", price: 260},
	{id: 40, url: img1, title: "bomber shivan black",season: "winter",type: "head", price: 400},
	{id: 41, url: img3, title: "bomber shivan black",season: "winter",type: "torso", price: 100},
	{id: 42, url: img3, title: "bomber shivan black",season: "winter",type: "head", price: 100},
	{id: 43, url: img2, title: "bomber shivan black",season: "winter",type: "head", price: 400},
	{id: 44, url: img3, title: "bomber shivan black",season: "spring",type: "head", price: 100},
	{id: 45, url: img4, title: "bomber shivan black",season: "spring",type: "head", price: 700},
	{id: 46, url: img1, title: "bomber shivan black",season: "winter",type: "head", price: 260},
	{id: 47, url: img2, title: "bomber shivan black",season: "winter",type: "head", price: 400},
	{id: 48, url: img3, title: "bomber shivan black",season: "winter",type: "torso", price: 100},
	{id: 49, url: img3, title: "bomber shivan black",season: "winter",type: "head", price: 100},
	{id: 50, url: img2, title: "bomber shivan black",season: "winter",type: "head", price: 400},
	{id: 51, url: img3, title: "bomber shivan black",season: "spring",type: "head", price: 100},
	{id: 52, url: img4, title: "bomber shivan black",season: "spring",type: "head", price: 700},
	{id: 53, url: img1, title: "bomber shivan black",season: "winter",type: "head", price: 260},
	{id: 54, url: img2, title: "bomber shivan black",season: "winter",type: "head", price: 400},
	{id: 55, url: img3, title: "bomber shivan black",season: "winter",type: "torso", price: 100},
]